name: Nightly Builds
on:
  schedule:
    - cron: '0 0 * * *' # daily, at midnight UTC
  workflow_dispatch: { }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository  
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Install .NET 6"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: "Generate interop assemblies"
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/ubuntu:22.04
          options: -t -v ${{ github.workspace }}:/workspace -e STEAMCMD_USER_NAME=${{secrets.STEAMCMD_USER_NAME}} -e STEAMCMD_USER_PASSWORD=${{secrets.STEAMCMD_USER_PASSWORD}}
          run: |
            cd /workspace
            ./generate_game_assemblies.sh
      - name: "Create and upload package"
        if: github.ref == 'refs/heads/main'
        run: |
          dotnet pack -c Release --nologo -o work/ RogueGenesia.Mod
          dotnet nuget push work/RogueGenesia.Mod.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
          mv work/RogueGenesia.Mod.*.nupkg work/latest.nupkg
      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: latest.nupkg
          path: work/latest.nupkg
